config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :member_availabilities
  resources :member_skills
  resources :availabilities
  resources :skills
  
  put 'members/:id/associate_skill/:skill_id' => 'member#associate_skill'
  resources :members

  root 'home#index'

end

app/models/member_availability.rb
class MemberAvailability < ActiveRecord::Base
  belongs_to :member
  belongs_to :availability
end

app/controllers/member_availabilities_controller.rb
class MemberAvailabilitiesController < ApplicationController
  before_action :set_member_availability, only: [:show, :edit, :update, :destroy]

  # GET /member_availabilities
  # GET /member_availabilities.json
  def index
    @member_availabilities = MemberAvailability.all
  end

  # GET /member_availabilities/1
  # GET /member_availabilities/1.json
  def show
  end

  # GET /member_availabilities/new
  def new
    @member_availability = MemberAvailability.new
  end

  # GET /member_availabilities/1/edit
  def edit
  end

  # POST /member_availabilities
  # POST /member_availabilities.json
  def create
    @member_availability = MemberAvailability.new(member_availability_params)

    respond_to do |format|
      if @member_availability.save
        format.html { redirect_to @member_availability, notice: 'Member availability was successfully created.' }
        format.json { render :show, status: :created, location: @member_availability }
      else
        format.html { render :new }
        format.json { render json: @member_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_availabilities/1
  # PATCH/PUT /member_availabilities/1.json
  def update
    respond_to do |format|
      if @member_availability.update(member_availability_params)
        format.html { redirect_to @member_availability, notice: 'Member availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_availability }
      else
        format.html { render :edit }
        format.json { render json: @member_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_availabilities/1
  # DELETE /member_availabilities/1.json
  def destroy
    @member_availability.destroy
    respond_to do |format|
      format.html { redirect_to member_availabilities_url, notice: 'Member availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_availability
      @member_availability = MemberAvailability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_availability_params
      params.require(:member_availability).permit(:member_id, :availability_id)
    end
end

app/helpers/member_availabilities_helper.rb
module MemberAvailabilitiesHelper
end

app/views/member_availabilities/_form.html.erb
<%= form_for(@member_availability) do |f| %>
  <% if @member_availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_availability.errors.count, "error") %> prohibited this member_availability from being saved:</h2>

      <ul>
      <% @member_availability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :availability_id %><br>
    <%= f.text_field :availability_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/member_availabilities/edit.html.erb
<h1>Editing Member Availability</h1>

<%= render 'form' %>

<%= link_to 'Show', @member_availability %> |
<%= link_to 'Back', member_availabilities_path %>

app/views/member_availabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Member Availabilities</h1>

<table>
  <thead>
    <tr>
      <th>Member</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @member_availabilities.each do |member_availability| %>
      <tr>
        <td><%= member_availability.member %></td>
        <td><%= member_availability.availability %></td>
        <td><%= link_to 'Show', member_availability %></td>
        <td><%= link_to 'Edit', edit_member_availability_path(member_availability) %></td>
        <td><%= link_to 'Destroy', member_availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member availability', new_member_availability_path %>

app/views/member_availabilities/new.html.erb
<h1>New Member Availability</h1>

<%= render 'form' %>

<%= link_to 'Back', member_availabilities_path %>

app/views/member_availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @member_availability.member %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @member_availability.availability %>
</p>

<%= link_to 'Edit', edit_member_availability_path(@member_availability) %> |
<%= link_to 'Back', member_availabilities_path %>