config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :member_availabilities
  resources :member_skills
  resources :availabilities
  resources :skills
  
  put 'members/:id/associate_skill/:skill_id' => 'member#associate_skill'
  resources :members

  root 'home#index'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  has_many :member_availabilities
  has_many :members, through: :member_availabilities
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: [:show, :edit, :update, :destroy]

  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(availability_params)

    respond_to do |format|
      if @availability.save
        format.html { redirect_to @availability, notice: 'Availability was successfully created.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1
  # PATCH/PUT /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to @availability, notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: 'Availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def availability_params
      params.require(:availability).permit(:name)
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_for(@availability) do |f| %>
  <% if @availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
      <% @availability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Editing Availability</h1>

<%= render 'form' %>

<%= link_to 'Show', @availability %> |
<%= link_to 'Back', availabilities_path %>

app/views/availabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Availabilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= availability.name %></td>
        <td><%= link_to 'Show', availability %></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td><%= link_to 'Destroy', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availability', new_availability_path %>

app/views/availabilities/new.html.erb
<h1>New Availability</h1>

<%= render 'form' %>

<%= link_to 'Back', availabilities_path %>

app/views/availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @availability.name %>
</p>

<%= link_to 'Edit', edit_availability_path(@availability) %> |
<%= link_to 'Back', availabilities_path %>